Import("env")

print()
print("================= Pigatron Industries ==================")
print()
print(env.Dump())
print()

if 'BUILD_FLAGS' in env:

    includes = ""
    registers = ""

    for buildFlag in env['BUILD_FLAGS']:
        print(buildFlag)
        if buildFlag.startswith('-DAPP'):
            print("Adding App: " + buildFlag)
            appFlags = buildFlag.split("/")
            includes = includes + "#include \"controllers/" + appFlags[1].lower() + "/"+ appFlags[1] + "Controller.h\"\n"
            includes = includes + appFlags[1] + "Controller " + appFlags[1] + "_;\n"
            registers = registers + "    MainController::instance.registerController(" + appFlags[1] + "_);\n"

    f = open("src/apps.h", "w")
    f.write("/* autogenerated */\n")
    f.write("#ifndef apps_h\n")
    f.write("#define apps_h\n")
    f.write(includes)
    f.write("void registerApps() {\n")
    f.write(registers)
    f.write("}\n")
    f.write("#endif\n")
    f.close()

print()
print("================= Pigatron Industries ==================")
print()