Import("env")

print()
print("================= Pigatron Industries ==================")
print()
print(env.Dump())
print()

if 'BUILD_FLAGS' in env:

    includes = ""
    typedef = ""
    index = 0

    for buildFlag in env['BUILD_FLAGS']:
        print(buildFlag)
        if buildFlag.startswith('-DAPP'):
            print("Adding App: " + buildFlag)
            appFlags = buildFlag.split("/")
            includes = includes + "#include \"controllers/" + appFlags[1].lower() + "/"+ appFlags[1] + "Controller.h\"\n"
            if index > 0:
                typedef = typedef + ", \\\n"
            typedef = typedef + appFlags[1] + "Controller"
            index += 1

    f = open("src/apps.h", "w")
    f.write("/* autogenerated */\n")
    f.write("#ifndef apps_h\n")
    f.write("#define apps_h\n")
    f.write(includes)
    f.write("#define CONTROLLERS \\\n")
    f.write(typedef)
    f.write("\n")
    f.write("#endif\n")
    f.close()

print()
print("================= Pigatron Industries ==================")
print()